In [1]:
import glob

In [2]:
len(glob.glob("./data/**/train/**/*.JPEG", recursive=False) )

0

In [3]:
import torchvision.datasets as datasets
import torchvision.transforms as transforms

# Define transformations to apply to the images
transform = transforms.Compose([
    transforms.Resize((256, 256)),  # Resize images to 256x256
    transforms.CenterCrop(224),      # Crop the center 224x224 region
    transforms.ToTensor(),           # Convert images to PyTorch tensors
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])  # Normalize images
])

# Path to the root directory containing subdirectories for each class
root_dir = "./data/tiny-imagenet-200/train/"

# Create an ImageFolder dataset
image_dataset = datasets.ImageFolder(root=root_dir, transform=transform)

In [4]:
image_dataset

Dataset ImageFolder
    Number of datapoints: 100000
    Root location: ./data/tiny-imagenet-200/train/
    StandardTransform
Transform: Compose(
               Resize(size=(256, 256), interpolation=bilinear, max_size=None, antialias=warn)
               CenterCrop(size=(224, 224))
               ToTensor()
               Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
           )

In [5]:
from torchvision.models import resnet50, ResNet50_Weights

model = resnet50(weights=ResNet50_Weights.IMAGENET1K_V2)

In [6]:
import torch
x = torch.randn(32, 3, 224, 224)
for name, module in model.named_children():
    if name == 'fc':
        x = torch.flatten(x, start_dim=1)
        print(x.size())
    x = module(x)
    print(name, ":\t",  x.size())

conv1 :	 torch.Size([32, 64, 112, 112])
bn1 :	 torch.Size([32, 64, 112, 112])
relu :	 torch.Size([32, 64, 112, 112])
maxpool :	 torch.Size([32, 64, 56, 56])
layer1 :	 torch.Size([32, 256, 56, 56])
layer2 :	 torch.Size([32, 512, 28, 28])
layer3 :	 torch.Size([32, 1024, 14, 14])
layer4 :	 torch.Size([32, 2048, 7, 7])
avgpool :	 torch.Size([32, 2048, 1, 1])
torch.Size([32, 2048])
fc :	 torch.Size([32, 1000])


In [7]:
model.eval()

ResNet(
  (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU(inplace=True)
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (layer1): Sequential(
    (0): Bottleneck(
      (conv1): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv3): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn3): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (downsample): Sequential(
        (0): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 

In [8]:
for name, param in model.named_parameters():
    print(name, param.size())

conv1.weight torch.Size([64, 3, 7, 7])
bn1.weight torch.Size([64])
bn1.bias torch.Size([64])
layer1.0.conv1.weight torch.Size([64, 64, 1, 1])
layer1.0.bn1.weight torch.Size([64])
layer1.0.bn1.bias torch.Size([64])
layer1.0.conv2.weight torch.Size([64, 64, 3, 3])
layer1.0.bn2.weight torch.Size([64])
layer1.0.bn2.bias torch.Size([64])
layer1.0.conv3.weight torch.Size([256, 64, 1, 1])
layer1.0.bn3.weight torch.Size([256])
layer1.0.bn3.bias torch.Size([256])
layer1.0.downsample.0.weight torch.Size([256, 64, 1, 1])
layer1.0.downsample.1.weight torch.Size([256])
layer1.0.downsample.1.bias torch.Size([256])
layer1.1.conv1.weight torch.Size([64, 256, 1, 1])
layer1.1.bn1.weight torch.Size([64])
layer1.1.bn1.bias torch.Size([64])
layer1.1.conv2.weight torch.Size([64, 64, 3, 3])
layer1.1.bn2.weight torch.Size([64])
layer1.1.bn2.bias torch.Size([64])
layer1.1.conv3.weight torch.Size([256, 64, 1, 1])
layer1.1.bn3.weight torch.Size([256])
layer1.1.bn3.bias torch.Size([256])
layer1.2.conv1.weight tor

In [9]:
from torchvision.models import resnet50

# Create ResNet model
model = resnet50(pretrained=True)

d:\software\anaconda3\envs\PyTorch\lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
d:\software\anaconda3\envs\PyTorch\lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet50_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet50_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)


In [10]:
x = torch.randn(32, 3, 224, 224)
for name, module in model.named_children():
    x = module(x)
    print(name, ":\t",  x.size())

conv1 :	 torch.Size([32, 64, 112, 112])
bn1 :	 torch.Size([32, 64, 112, 112])
relu :	 torch.Size([32, 64, 112, 112])
maxpool :	 torch.Size([32, 64, 56, 56])
layer1 :	 torch.Size([32, 256, 56, 56])
layer2 :	 torch.Size([32, 512, 28, 28])
layer3 :	 torch.Size([32, 1024, 14, 14])
layer4 :	 torch.Size([32, 2048, 7, 7])
avgpool :	 torch.Size([32, 2048, 1, 1])


RuntimeError: mat1 and mat2 shapes cannot be multiplied (65536x1 and 2048x1000)

In [21]:
import torch

In [25]:
N = 5
random_value = torch.rand((1000, 1000))
random_value

tensor([[0.7086, 0.3411, 0.4974,  ..., 0.2733, 0.5600, 0.6204],
        [0.4899, 0.9759, 0.6509,  ..., 0.6127, 0.5462, 0.9471],
        [0.4860, 0.5103, 0.4107,  ..., 0.7243, 0.4358, 0.6537],
        ...,
        [0.7042, 0.9854, 0.2841,  ..., 0.6334, 0.4359, 0.9281],
        [0.9343, 0.1604, 0.3699,  ..., 0.9198, 0.9806, 0.7741],
        [0.4147, 0.0402, 0.5161,  ..., 0.0281, 0.7010, 0.2871]])

In [26]:
classes = torch.floor(random_value * N)
classes

tensor([[3., 1., 2.,  ..., 1., 2., 3.],
        [2., 4., 3.,  ..., 3., 2., 4.],
        [2., 2., 2.,  ..., 3., 2., 3.],
        ...,
        [3., 4., 1.,  ..., 3., 2., 4.],
        [4., 0., 1.,  ..., 4., 4., 3.],
        [2., 0., 2.,  ..., 0., 3., 1.]])

In [27]:
torch.unique(classes, return_counts=True)

(tensor([0., 1., 2., 3., 4.]),
 tensor([199847, 200107, 199749, 200481, 199816]))